<?
$PERM["personal"]["6"]="W";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["6"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["6"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["6"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["6"]="W";
$PERM["index.php"]["8"]="W";
$PERM["desktop_app"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["/"]["*"]="R";
?>